[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
refreshPeriod = "168h"

[".config/fzf-extensions/fzf-git.sh"]
type = "git-repo"
url = "https://github.com/junegunn/fzf-git.sh.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-history-substring-search.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-z"]
type = "git-repo"
url = "https://github.com/agkozak/zsh-z.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
type = "git-repo"
url = "https://github.com/jeffreytse/zsh-vi-mode.git"
refreshPeriod = "168h"
